using System;
using System.Collections.Generic;
using System.Drawing;
using System.Text;

namespace voltorbflip
{
    class VoltorbFlipColors
    {
        public static readonly Color _WILDCARD = Color.Empty;
        public static readonly Color _WHITE = Color.FromArgb(255, 214, 239, 231);
        public static readonly Color _BLUE = Color.FromArgb(255, 49, 107, 231);
        public static readonly Color _BLACK = Color.FromArgb(255, 66, 66, 66);
        public static readonly Color _BORDERBLACK = Color.FromArgb(255, 41, 41, 41);
        public static readonly Color _LIGHTGREEN = Color.FromArgb(255, 41, 165, 107);
        public static readonly Color _DARKGREEN = Color.FromArgb(255, 24, 132, 99);
        public static readonly Color _BROWN = Color.FromArgb(255, 165, 90, 82);
        public static readonly Color _LIGHTBROWN = Color.FromArgb(255, 189, 140, 132);

        public static readonly Color[,] BOTTOMRIGHT = new Color[15, 15]
        {
            {_BLUE,_BLUE,_BLUE,_BLUE, _BLACK,_BLACK,_BLACK,_BLACK,_BLACK,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN, },
            {_BLUE,_BLUE,_BLUE,_BLUE, _BLACK,_BLACK,_BLACK,_BLACK,_BLACK,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN, },
            {_BLACK,_BLACK,_BLACK,_BLACK, _BLACK,_BLACK,_BLACK,_BLACK,_BLACK,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN, },
            {_BLACK,_BLACK,_BLACK,_BLACK, _BLACK,_BLACK,_BLACK,_BLACK,_BLACK,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN, },
            {_BLACK,_BLACK,_BLACK,_BLACK, _BLACK,_BLACK,_BLACK,_LIGHTGREEN,_LIGHTGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN, },
            {_BLACK,_BLACK,_BLACK,_BLACK, _BLACK,_BLACK,_BLACK,_LIGHTGREEN,_LIGHTGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN, },
            {_BLACK,_BLACK,_BLACK,_BLACK, _BLACK,_BLACK,_BLACK,_LIGHTGREEN,_LIGHTGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN, },
            {_LIGHTGREEN, _LIGHTGREEN,_LIGHTGREEN,_LIGHTGREEN, _LIGHTGREEN,_LIGHTGREEN,_LIGHTGREEN,_LIGHTGREEN,_LIGHTGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN, },
            {_LIGHTGREEN, _LIGHTGREEN,_LIGHTGREEN,_LIGHTGREEN, _LIGHTGREEN,_LIGHTGREEN,_LIGHTGREEN,_LIGHTGREEN,_LIGHTGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN, },
            {_LIGHTGREEN, _LIGHTGREEN,_LIGHTGREEN,_LIGHTGREEN, _LIGHTGREEN,_LIGHTGREEN,_LIGHTGREEN,_LIGHTGREEN,_LIGHTGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN, },
            {_LIGHTGREEN, _LIGHTGREEN,_LIGHTGREEN,_LIGHTGREEN, _LIGHTGREEN,_LIGHTGREEN,_LIGHTGREEN,_LIGHTGREEN,_LIGHTGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN, },
            {_LIGHTGREEN, _LIGHTGREEN,_LIGHTGREEN,_LIGHTGREEN, _LIGHTGREEN,_LIGHTGREEN,_LIGHTGREEN,_LIGHTGREEN,_LIGHTGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN, },
            {_LIGHTGREEN, _LIGHTGREEN,_LIGHTGREEN,_LIGHTGREEN, _LIGHTGREEN,_LIGHTGREEN,_LIGHTGREEN,_LIGHTGREEN,_LIGHTGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN, },
            {_LIGHTGREEN, _LIGHTGREEN,_LIGHTGREEN,_LIGHTGREEN, _LIGHTGREEN,_LIGHTGREEN,_LIGHTGREEN,_LIGHTGREEN,_LIGHTGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN, },
            {_LIGHTGREEN, _LIGHTGREEN,_LIGHTGREEN,_LIGHTGREEN, _LIGHTGREEN,_LIGHTGREEN,_LIGHTGREEN,_LIGHTGREEN,_LIGHTGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN, },
        };

        public static readonly Color[,] TOPLEFT = new Color[14, 14]
        {
            {_DARKGREEN, _DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN },
            {_DARKGREEN, _DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN },
            {_DARKGREEN, _DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN },
            {_DARKGREEN, _DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN, _DARKGREEN},
            {_DARKGREEN, _DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN },
            {_DARKGREEN, _DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN, _DARKGREEN},
            {_DARKGREEN, _DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_LIGHTGREEN },
            {_DARKGREEN, _DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_LIGHTGREEN },
            {_DARKGREEN, _DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_LIGHTGREEN,_LIGHTGREEN,_LIGHTGREEN,_LIGHTGREEN,_LIGHTGREEN, _LIGHTGREEN},
            {_DARKGREEN, _DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_LIGHTGREEN,_LIGHTGREEN,_LIGHTGREEN,_LIGHTGREEN,_LIGHTGREEN, _LIGHTGREEN},
            {_DARKGREEN, _DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_LIGHTGREEN,_LIGHTGREEN,_LIGHTGREEN,_LIGHTGREEN,_LIGHTGREEN, _LIGHTGREEN},
            {_DARKGREEN, _DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_LIGHTGREEN,_LIGHTGREEN,_LIGHTGREEN,_LIGHTGREEN,_LIGHTGREEN,_LIGHTGREEN },
            {_DARKGREEN, _DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_LIGHTGREEN,_LIGHTGREEN,_LIGHTGREEN,_LIGHTGREEN,_LIGHTGREEN, _LIGHTGREEN },
            {_DARKGREEN, _DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_DARKGREEN,_LIGHTGREEN,_LIGHTGREEN,_LIGHTGREEN,_LIGHTGREEN,_LIGHTGREEN,_LIGHTGREEN,_LIGHTGREEN, _LIGHTGREEN },
        };

        public static readonly Color[,] FLIPPED_TOPLEFT = new Color[2, 2]
        {
            {_BROWN, _BROWN,},
            {_BROWN, _LIGHTBROWN,},
        };

        //public static readonly Color[,] UNFLIPPED_BOX = new Color[2, 2]
        //{
        //    {_DARKGREEN, _LIGHTGREEN,},
        //    {_LIGHTGREEN, _DARKGREEN,},
        //};
        public static readonly Color[,] UNFLIPPED_BOX = new Color[2, 2]
        {
            {_BORDERBLACK, _BORDERBLACK,},
            {_BORDERBLACK, _DARKGREEN,},
        };
    }
}
